### ISSUE TITLE
ReferenceError: document is not defined (in node)

### ISSUE THREAD

**Issue by macgyver** [lifaon74/url-polyfill#16]
Just curious - is this meant to work in node? I was hoping it would so I can run unit tests there without mocking out the URL/URLSearchParams APIs. This is the error:
```
$ cat test.js
require('url-polyfill')
u = new URL('https://example.com/')
$ node test.js
/Users/jrz/node_modules/url-polyfill/url-polyfill.js:174
      var doc = document.implementation.createHTMLDocument('');
                                        ^

ReferenceError: document is not defined
    at new URL (/Users/jrz/node_modules/url-polyfill/url-polyfill.js:174:41)
    at Object.<anonymous> (/Users/jrz/test.js:3:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
$ node -v
v6.12.0
```

**Comment by lifaon74** [comment]
A full WHATWG implementation can be found here : https://github.com/lifaon74/url-polyfill/files/1572997/url.zip for node version older than 8.0.0

**Comment by macgyver** [comment]
oh interesting - so if I upgrade to a newer version of node I can use the standard `url-polyfill` from npm?

**Comment by lifaon74** [comment]
No, the lib I shared upper is a full implementation of the WHATWG URL in js. It means it could work for any version of node or browsers.

In an other hand, node starting from v8.0.0 includes URL by default: https://nodejs.org/api/url.html

**Comment by macgyver** [comment]
Oh gotcha - that's awesome, thanks so much!
